spring:
  application:
    name: smart-inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db
    username: postgres
    password: huong123
jwt:
  secret: "rLMd+H7azT+grHFt1rd6XHoO/0gD6cIl1nT7F71Xb08C0EzNKsIX/IHA/lbgIsdB"
  expiration: 172800000
logging:
  level:
    org.springframework.security: DEBUG
security:
  whitelist:
    - "/api/auth/**"
    - "/api/public/**"
    - "/actuator/**"