server:
  port: 8083
spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/patient-db
    username: postgres
    password: huong123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true