server:
  port: 8084
spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment-db
    username: postgres
    password: huong123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
